spring:
  profiles:
    active: local
    hibernate:
      format_sql: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      default_batch_fetch_size: 100

# local
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      path: /h2
      enabled: true

# dev
---
spring:
  profiles: dev

# pro
---
spring:
  profiles: pro


